"""
Auto-generated database migration.
Run with: alembic upgrade head
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '001_initial_schema'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Create all tables from models."""
    # Schemas
    op.execute("CREATE SCHEMA IF NOT EXISTS hse")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS uuid-ossp")

    # Tables will be auto-generated by SQLAlchemy models via Flask-Migrate/Alembic
    # In production, we use: alembic revision --autogenerate -m "message"
    # For now, rely on db.create_all() in application startup


def downgrade() -> None:
    """Drop all tables."""
    op.execute("DROP SCHEMA IF EXISTS hse CASCADE")
